server:
  servlet:
    context-path: /msh

management:
  endpoint:
    info:
        enabled: true
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: health
  info:
    git:
      mode: full
logging:
  level:
    ROOT: DEBUG
